/**
 * Gets the autogenerated release notes from GitHub and makes them more organized.
 * Removes all items that start with "Bump" and sorts the rest according to their tags.
 * Example:
 *      <input>
 *          * Bump ABC from 1.0 to 1.1
 *          * `Feature` Feature 1
 *          * `Chore` Chore 1
 *          * `Improvement` Improvement 1
 *          * Bump XYZ from 1.0 to 1.1
 *          * `Chore` Chore 2
 *      </input>
 *
 *      <output>
 *          ### Features
 *          * `Feature` Feature 1
 *
 *          ### Improvements
 *          * `Improvement` Improvement 1
 *
 *          ### Chores
 *          * `Chore` Chore 1
 *          * `Chore` Chore 2
 *     </output>
 */
fun sortReleaseNotes(input: String): String {
    val lines = input.lines()
    val sortedLines = lines.filter { !it.startsWith("* Bump") }
        .groupBy { it.substringAfter("`").substringBefore("`") }
        .map { (tag, items) ->
            "### $tag\n" + items.joinToString("\n")
        }
    return sortedLines.joinToString("\n\n")
}
