services:
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql

  artemis-app:
    extends:
      file: ./artemis.yml
      service: artemis-app
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - artemis_e2e_config.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    expose:
      - "5005"
    networks:
      - artemis

  artemis-app-setup:
    image: ellerbrock/alpine-bash-curl-ssl:latest
    depends_on:
      artemis-app:
        condition: service_healthy
    volumes:
      - ./create_test_users.sh:/create_test_users.sh
    entrypoint: /bin/bash -c "/bin/bash /create_test_users.sh artemis-app:8080"
    networks:
      - artemis

networks:
  artemis:
    driver: "bridge"
    name: artemis

volumes:
  artemis-mysql-data-android:
    name: artemis-mysql-data-android
  artemis-data:
    name: artemis-data
