package de.tum.informatics.www1.artemis.native_app.android.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF3E8ACC)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF2779BA)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF48607B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCDE3FF)
val onSecondaryContainerLight = Color(0xFF314962)
val tertiaryLight = Color(0xFF713983)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF995EAA)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF000000)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF000000)
val surfaceVariantLight = Color(0xFFDCE3EE)
val onSurfaceVariantLight = Color(0xFF404750)
val outlineLight = Color(0xFF717881)
val outlineVariantLight = Color(0xFFC0C7D2)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3135)
val inverseOnSurfaceLight = Color(0xFFEFF1F6)
val inversePrimaryLight = Color(0xFF9ACBFF)
val surfaceDimLight = Color(0xFFD8DAE0)
val surfaceBrightLight = Color(0xFFF8F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F3F9)
val surfaceContainerLight = Color(0xfff2f2f2)
val surfaceContainerHighLight = Color(0xFFE6E8EE)
val surfaceContainerHighestLight = Color(0xFFE0E2E8)

val primaryDark = Color(0xFF9ACBFF)
val onPrimaryDark = Color(0xFF003355)
val primaryContainerDark = Color(0xFF2779BA)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFB0C9E7)
val onSecondaryDark = Color(0xFF18324A)
val secondaryContainerDark = Color(0xFF263F58)
val onSecondaryContainerDark = Color(0xFFBAD3F2)
val tertiaryDark = Color(0xFFF0B0FF)
val onTertiaryDark = Color(0xFF4D1560)
val tertiaryContainerDark = Color(0xFF995EAA)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF000000)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF101418)
val onSurfaceDark = Color(0xFFE0E2E8)
val surfaceVariantDark = Color(0xFF404750)
val onSurfaceVariantDark = Color(0xFFC0C7D2)
val outlineDark = Color(0xFF8A919B)
val outlineVariantDark = Color(0xFF404750)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E2E8)
val inverseOnSurfaceDark = Color(0xFF2D3135)
val inversePrimaryDark = Color(0xFF00629F)
val surfaceDimDark = Color(0xFF101418)
val surfaceBrightDark = Color(0xFF36393E)
val surfaceContainerLowestDark = Color(0xFF0B0E12)
val surfaceContainerLowDark = Color(0xFF191C20)
val surfaceContainerDark = Color(0xff333333)
val surfaceContainerHighDark = Color(0xFF272A2F)
val surfaceContainerHighestDark = Color(0xFF32353A)








