name: End-To-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'readme.md'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/build.yml'

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      USER_1_USERNAME: aa01aaa
      USER_1_PASSWORD: test_user_1_password
      USER_2_USERNAME: aa02aaa
      USER_2_DISPLAY_NAME: Test User2
      USER_3_USERNAME: aa03aaa
      SERVER_URL: http://localhost:8080
      DEFAULT_TIMEOUT: 30000
      ADMIN_USERNAME: artemis_admin
      ADMIN_PASSWORD: artemis_admin
      robolectric.logging.enabled: true

    steps:
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Checkout Code
        uses: actions/checkout@v2

      # Issuelink: https://github.com/nektos/act/issues/1172#issuecomment-1699598124
      - name: Set up Android SDK
        if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
        uses: android-actions/setup-android@v2

      - name: Start Artemis Server
        run: docker compose -f docker/e2e-tests.yml up artemis-app-setup

      - name: Build
        run: ./gradlew test -Dskip.debugVariants=true -Dskip.flavor.unrestricted=true -Dskip.flavor.beta=true