name: End To End Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  end-to-end:
    runs-on: [self-hosted, android]
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Gather tag parameter values
        id: calc_tag
        run: echo "image_tag=$(./scripts/calc_docker_image_tag.sh)" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull android base image
        run: docker pull $(${{ secrets.REGISTRY_HOST }}/artemis_android_build_image:${{ steps.calc_tag.outputs.image_tag }})

      - name: Build and publish new android base image
        uses: docker/build-push-action@v5
        if: failure()
        with:
          file: Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_HOST }}/artemis_android_build_image:${{ steps.calc_tag.outputs.image_tag }}

      - name: Run end to end tests.
        run: docker compose -f docker/e2e-tests.yml up artemis-android-e2e --abort-on-container-exit --force-recreate

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: End To End Test Results
          path: test-outputs/**/*.xml
          reporter: java-junit