name: Artemis Android End To End Tests

on:
  pull_request:
    paths-ignore:
      - 'readme.md'
      - 'LICENSE'
      - '.github/**'
      - '!.github/workflows/e2e-tests.yml'

jobs:
  e2e-tests:
    name: Run End To End Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Docker Compose
        run: docker compose -f docker/e2e-tests.yml up artemis-android-e2e --abort-on-container-exit --force-recreate

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Android End To End Tests
          path: test-outputs/**/*.xml
          reporter: java-junit