name: End To End Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  end-to-end-tests:
    name: End To End Tests
    runs-on: [self-hosted, ase-large-android-sdk-34]
    timeout-minutes: 60

    steps:
      - name: Set Android Sdk Env
        run: export ANDROID_HOME=/usr/lib/android-sdk

      - uses: actions/checkout@v4

      - name: Set local.properties
        run: echo "sdk.dir=/usr/lib/android-sdk" > local.properties

      - name: Gradle Wrapper Verification
        uses: gradle/wrapper-validation-action@v1

        # Sanity cleanup
      - name: Stop all running docker containers
        run: docker stop $(docker ps -a -q)

      - name: Remove all docker containers
        run: docker rm $(docker ps -qa)
        if: success() || failure()

      - name: Launch docker containers
        run: docker compose -f docker/e2e-tests.yml up -d artemis-app-setup
        if: success() || failure()

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: run tests
        run: ./gradlew test --max-workers=4 -Dskip.unit-tests=true -Dskip.e2e=false -Dskip.debugVariants=true -Dskip.flavor.unrestricted=true -Dskip.flavor.beta=true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Android End To End Test Results
          path: test-outputs/**/*.xml
          reporter: java-junit

      - name: Cleanup -> Stop all running docker containers
        run: docker stop $(docker ps -a -q)

      - name: Cleanup -> Remove all docker containers
        run: docker rm $(docker ps -qa)
        if: success() || failure()