name: JUnit Tests (no end-to-end)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  jUnit:
    name: JUnit Tests
    runs-on: [self-hosted, ase-large-android-sdk-35]
    timeout-minutes: 60

    steps:
      - name: Set Android Sdk Env
        run: export ANDROID_HOME=/usr/lib/android-sdk

      - uses: actions/checkout@v4

      - name: Set local.properties
        run: echo "sdk.dir=/usr/lib/android-sdk" > local.properties

      - name: Gradle Wrapper Verification
        uses: gradle/wrapper-validation-action@v1

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: run tests
        run: ./gradlew test -Dskip.unit-tests=false -Dskip.e2e=true -Dskip.debugVariants=true -Dskip.flavor.unrestricted=true -Dskip.flavor.beta=true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Android Unit Tests
          path: test-outputs/**/*.xml
          reporter: java-junit
          fail-on-empty: 'false'
